import {
  JavascriptOriginal,
  TypescriptOriginal,
  ReactOriginal,
  ViteOriginal,
  NodejsOriginal,
  ExpressOriginal,
  MongodbOriginal,
  PostgresqlOriginal,
  TailwindcssOriginal,
  GitOriginal,
  JavaOriginal,
  SpringOriginal,
  QuarkusOriginal,
  DockerOriginal,
  LinuxOriginal,
  MysqlOriginal,
  NestjsOriginal,
  HibernateOriginal,
  RabbitmqOriginal,
  JunitOriginal,
  GradleOriginal,
  MavenOriginal,
  KubernetesOriginal,
  AzureOriginal,
  GithubOriginal,
  RedisOriginal,
} from "devicons-react";

export const iconMap: Record<string, React.ComponentType<{ size?: number }>> = {
  javascript: JavascriptOriginal,
  typescript: TypescriptOriginal,
  react: ReactOriginal,
  vite: ViteOriginal,
  nodejs: NodejsOriginal,
  expressjs: ExpressOriginal,
  mongodb: MongodbOriginal,
  postgresql: PostgresqlOriginal,
  sqlserver: MysqlOriginal,
  mysql: MysqlOriginal,
  tailwindcss: TailwindcssOriginal,
  git: GitOriginal,
  github: GithubOriginal,
  java: JavaOriginal,
  spring: SpringOriginal,
  quarkus: QuarkusOriginal,
  docker: DockerOriginal,
  kubernetes: KubernetesOriginal,
  linux: LinuxOriginal,
  nestjs: NestjsOriginal,
  hibernate: HibernateOriginal,
  rabbitmq: RabbitmqOriginal,
  junit: JunitOriginal,
  gradle: GradleOriginal,
  maven: MavenOriginal,
  azure: AzureOriginal,
  redis: RedisOriginal,
};

export const getDevicon = (iconName?: string) => {
  if (!iconName) return undefined;
  return iconMap[iconName.toLowerCase()];
};
